#!/usr/bin/env bash
# Batch launcher for OCDockerPipeline/Snakemake.
#
# What this script does:
# - Splits the global `rule all` target set into Snakemake native `--batch all=i/N` partitions.
# - Runs one or many batch indices sequentially.
# - Propagates user Snakemake args after `--`.
# - Forces `pipeline_export_database_csv=false` during batch runs so each partition stays local.
#
# Why this wrapper exists:
# - Large datasets are easier to recover/restart when processed in bounded chunks.
# - Batch-level retries are much cheaper than re-running a giant monolithic execution.
# - It standardizes runtime temp/cache paths and optional conda invocation.
#
# Important behavior:
# - This script does NOT merge many batches into one Snakemake workflow UUID.
# - It intentionally launches one Snakemake invocation per batch index.
# - Existing completed outputs are reused by Snakemake unless rerun flags request otherwise.
set -euo pipefail
# shellcheck disable=SC2034
# SC2034 note: some variables are intentionally initialized and conditionally used.

usage() {
    cat <<'USAGE'
Run OCDockerPipeline in batches via native Snakemake --batch on rule `all`.

Usage:
  scripts/run_target_batches.sh [batch mode options] [runner options] -- [snakemake args...]

Batch mode (pick exactly one):
  --total-batches N         Fractional mode (runs all=1/N, 2/N, ...)
  --batch-size N            Approximate fixed-size mode (derives total batches)

Batch range:
  --from I                  First batch index to run (1-based, default: 1)
  --to J                    Last batch index to run (inclusive)
                            Fractional mode default: N
                            Fixed-size mode default: --from value
  --all                     In fixed-size mode, run from --from through the
                            derived final batch index.

Fixed-size helpers:
  --total-targets N         Total targets to use for --batch-size conversion
                            (if omitted, inferred from .snakemake/target_discovery_cache.json)

Runner options:
  --snakefile PATH          Snakefile path (default: snakefile)
  --snakemake-bin BIN       Snakemake executable (default: snakemake)
  --conda-env NAME          Run as: conda run -n NAME snakemake
  --cache-root PATH         XDG cache root used for each run (default: /tmp)
  --tmp-root PATH           TMPDIR used for each run (default: /tmp)
  --dry-run                 Add -n to each run
  -h, --help                Show this help

Examples:
  # Tiny test: one small batch (approximately 5 targets)
  scripts/run_target_batches.sh --batch-size 5 --from 1 --to 1 -- --cores 8 --resources mem_mb=12000

  # Full run over 20 fractions
  scripts/run_target_batches.sh --total-batches 20 -- --cores 16 --resources mem_mb=28000 --keep-going

  # Full fixed-size run (all derived batches)
  scripts/run_target_batches.sh --batch-size 500 --all --conda-env ocdocker -- --cores 16 --resources mem_mb=28000 --keep-going

  # Same using conda env directly from script
  scripts/run_target_batches.sh --total-batches 20 --conda-env ocdocker -- --cores 16 --resources mem_mb=28000 --keep-going

Complete example:

  # Set up logging for a full fixed-size run with conda environment. Logs will be written to a timestamped file in logs/.
  LOG="logs/pipeline_all_batches_$(date +%F_%H-%M-%S).log"

  # Run the pipeline with nohup, logging, using a batch size of 500 and all derived batches, within the 'ocdocker' conda environment. Adjust Snakemake args as needed.
  nohup env XDG_CACHE_HOME=/tmp TMPDIR=/tmp ./scripts/run_target_batches.sh \
    --batch-size 500 --all --conda-env ocdocker -- \
    --logger snkmt \
    --logger-snkmt-db /data/hd4tb/OCDocker/OCDockerPipeline/.snakemake/snkmt.db \
    --cores 18 --resources mem_mb=28000 --keep-going \
    --rerun-incomplete --rerun-triggers mtime \
    > "$LOG" 2>&1 &

echo "Started. Tail with: tail -f $LOG"
USAGE
}

is_pos_int() {
    # Helper: strict positive integer checker used by argument validation.
    [[ "${1:-}" =~ ^[1-9][0-9]*$ ]]
}

fail() {
    # Consistent fatal error helper.
    echo "Error: $*" >&2
    exit 2
}

infer_total_targets_from_cache() {
    # In fixed-size mode, if `--total-targets` is omitted, we infer target count
    # from Snakemake discovery cache generated by previous DAG discovery.
    #
    # Expected JSON shape:
    #   { "targets": [ ... ] }
    #
    # We only need the length, not the target payload.
    local cache_json="${1:-.snakemake/target_discovery_cache.json}"
    [[ -f "$cache_json" ]] || fail "Cannot infer target count. Cache file not found: $cache_json"
    command -v python3 >/dev/null 2>&1 || fail "python3 is required to parse $cache_json"

    local count
    count="$(python3 - "$cache_json" <<'PY'
import json
import sys
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)
targets = payload.get("targets", [])
print(len(targets) if isinstance(targets, list) else 0)
PY
)"

    is_pos_int "$count" || fail "Invalid or empty target count in $cache_json"
    echo "$count"
}

total_batches=""
batch_size=""
total_targets=""
from_idx=1
to_idx=""
snakefile="snakefile"
snakemake_bin="snakemake"
conda_env=""
cache_root="/tmp"
tmp_root="/tmp"
dry_run=0
run_all=0
declare -a extra_args=()

# ---------------------------------------------------------------------------
# 1) Parse wrapper arguments until `--`.
#    Everything after `--` is forwarded verbatim to Snakemake.
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --total-batches)
            [[ $# -ge 2 ]] || fail "Missing value for --total-batches"
            total_batches="$2"
            shift 2
            ;;
        --batch-size)
            [[ $# -ge 2 ]] || fail "Missing value for --batch-size"
            batch_size="$2"
            shift 2
            ;;
        --total-targets)
            [[ $# -ge 2 ]] || fail "Missing value for --total-targets"
            total_targets="$2"
            shift 2
            ;;
        --from|--start)
            [[ $# -ge 2 ]] || fail "Missing value for --from"
            from_idx="$2"
            shift 2
            ;;
        --to|--end)
            [[ $# -ge 2 ]] || fail "Missing value for --to"
            to_idx="$2"
            shift 2
            ;;
        --snakefile)
            [[ $# -ge 2 ]] || fail "Missing value for --snakefile"
            snakefile="$2"
            shift 2
            ;;
        --snakemake-bin)
            [[ $# -ge 2 ]] || fail "Missing value for --snakemake-bin"
            snakemake_bin="$2"
            shift 2
            ;;
        --conda-env)
            [[ $# -ge 2 ]] || fail "Missing value for --conda-env"
            conda_env="$2"
            shift 2
            ;;
        --cache-root)
            [[ $# -ge 2 ]] || fail "Missing value for --cache-root"
            cache_root="$2"
            shift 2
            ;;
        --tmp-root)
            [[ $# -ge 2 ]] || fail "Missing value for --tmp-root"
            tmp_root="$2"
            shift 2
            ;;
        --dry-run)
            dry_run=1
            shift
            ;;
        --all)
            run_all=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            extra_args=("$@")
            break
            ;;
        *)
            fail "Unknown option: $1 (use --help)"
            ;;
    esac
done

# ---------------------------------------------------------------------------
# 2) Validate mode selection and numeric inputs.
# ---------------------------------------------------------------------------
if [[ -n "$total_batches" && -n "$batch_size" ]]; then
    fail "Use exactly one batching mode: --total-batches OR --batch-size"
fi
if [[ -z "$total_batches" && -z "$batch_size" ]]; then
    fail "Missing batching mode: provide --total-batches or --batch-size"
fi

is_pos_int "$from_idx" || fail "--from must be a positive integer"
if [[ -n "$to_idx" ]]; then
    is_pos_int "$to_idx" || fail "--to must be a positive integer"
fi

mode=""
if [[ -n "$total_batches" ]]; then
    # Fractional mode:
    # User already defines N batches. We run all=i/N.
    mode="fraction"
    is_pos_int "$total_batches" || fail "--total-batches must be a positive integer"
    if [[ -z "$to_idx" ]]; then
        to_idx="$total_batches"
    fi
    (( from_idx <= total_batches )) || fail "--from must be <= --total-batches"
    (( to_idx <= total_batches )) || fail "--to must be <= --total-batches"
else
    # Fixed-size mode:
    # Derive N from total target count and requested batch size.
    # Formula: ceil(total_targets / batch_size).
    mode="fixed_size"
    is_pos_int "$batch_size" || fail "--batch-size must be a positive integer"

    if [[ -z "$total_targets" ]]; then
        total_targets="$(infer_total_targets_from_cache)"
    fi
    is_pos_int "$total_targets" || fail "--total-targets must be a positive integer"

    total_batches="$(( (total_targets + batch_size - 1) / batch_size ))"
    if [[ -z "$to_idx" ]]; then
        # Default range behavior in fixed-size mode:
        # - with --all: run through the final derived batch
        # - without --all: run a single batch (--from only)
        if (( run_all )); then
            to_idx="$total_batches"
        else
            to_idx="$from_idx"
        fi
    fi
    (( from_idx <= total_batches )) || fail "--from must be <= derived total batches (${total_batches})"
    (( to_idx <= total_batches )) || fail "--to must be <= derived total batches (${total_batches})"
fi

(( from_idx <= to_idx )) || fail "--from must be <= --to"
[[ -f "$snakefile" ]] || fail "Snakefile not found: $snakefile"

# ---------------------------------------------------------------------------
# 3) Build the Snakemake executable prefix.
#    - If --conda-env is provided: use `conda run -n <env> snakemake`
#    - Else: execute the given snakemake binary directly.
# ---------------------------------------------------------------------------
declare -a snakemake_cmd=()
if [[ -n "$conda_env" ]]; then
    command -v conda >/dev/null 2>&1 || fail "conda not found but --conda-env was provided"
    snakemake_cmd=(conda run -n "$conda_env" snakemake)
else
    command -v "$snakemake_bin" >/dev/null 2>&1 || fail "Snakemake binary not found: $snakemake_bin"
    snakemake_cmd=("$snakemake_bin")
fi

# ---------------------------------------------------------------------------
# 4) Runtime path normalization.
#    Many tools in this stack write temp/cache files; using explicit roots helps
#    avoid stale locks/permission drift from prior sessions.
# ---------------------------------------------------------------------------
mkdir -p "$cache_root" "$tmp_root" >/dev/null 2>&1 || true
export XDG_CACHE_HOME="$cache_root"
export TMPDIR="$tmp_root"

# snkmt requires both flags. If DB path is provided without --logger,
# prepend --logger snkmt automatically for convenience.
has_logger=0
has_logger_snkmt_db=0
for arg in "${extra_args[@]}"; do
    case "$arg" in
        --logger|--logger=*)
            has_logger=1
            ;;
        --logger-snkmt-db|--logger-snkmt-db=*)
            has_logger_snkmt_db=1
            ;;
    esac
done
if (( has_logger_snkmt_db )) && (( ! has_logger )); then
    extra_args=(--logger snkmt "${extra_args[@]}")
    echo "Info: auto-added '--logger snkmt' because '--logger-snkmt-db' was provided."
fi

# ---------------------------------------------------------------------------
# 5) User-facing run summary before execution starts.
# ---------------------------------------------------------------------------
echo "Batch runner: mode=${mode}, range=${from_idx}-${to_idx}, snakefile=${snakefile}"
echo "Runtime paths: XDG_CACHE_HOME=${XDG_CACHE_HOME}, TMPDIR=${TMPDIR}"
if [[ "$mode" == "fixed_size" ]]; then
    echo "Derived batch conversion: total_targets=${total_targets}, batch_size=${batch_size}, total_batches=${total_batches}"
fi
if [[ ${#extra_args[@]} -gt 0 ]]; then
    echo "Forwarded Snakemake args: ${extra_args[*]}"
fi

# ---------------------------------------------------------------------------
# 6) Sequential batch execution loop.
#    Each iteration launches one Snakemake process:
#      snakemake -s <snakefile> --batch all=i/N [forwarded args...]
#
#    Notes:
#    - We always append `--config pipeline_export_database_csv=false`.
#      This prevents each partition from depending on a full-database CSV fan-in.
#    - On first failing batch, stop immediately with non-zero exit.
# ---------------------------------------------------------------------------
for (( idx=from_idx; idx<=to_idx; idx++ )); do
    batch_spec="all=${idx}/${total_batches}"

    echo
    echo "=== Running batch ${idx} (${batch_spec}) ($(date '+%Y-%m-%d %H:%M:%S')) ==="

    declare -a cmd=(
        "${snakemake_cmd[@]}"
        -s "$snakefile"
        --batch "$batch_spec"
    )
    if (( dry_run )); then
        cmd+=(-n)
    fi
    if [[ ${#extra_args[@]} -gt 0 ]]; then
        cmd+=("${extra_args[@]}")
    fi
    # Disable per-database CSV export in batch runs to avoid all-target fan-in
    # dependencies being reintroduced for each partition. Append it last so a
    # user-provided --config cannot re-enable CSV export accidentally.
    cmd+=(--config "pipeline_export_database_csv=false")

    if ! "${cmd[@]}"; then
        echo "Batch ${idx} failed. Stopping." >&2
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# 7) Finished all requested batch indices successfully.
# ---------------------------------------------------------------------------
echo
echo "All requested batches finished successfully."
